// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsctevoicfyqtyncnbse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzY3Rldm9pY2Z5cXR5bmNuYnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjcyOTMsImV4cCI6MjA2OTY0MzI5M30.3gdGjI8evCggup8n2H8ZwrDVCZoM4kJnG3JPJVxClfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});